language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7-dev" # 3.7 development branch

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - python setup.py install

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to run tests
script: pytest
