#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import os
import psoap

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    "sphinx.ext.napoleon",
    "sphinxarg.ext"
]

templates_path = ['.templates']

source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'PSOAP'
copyright = '2017, Ian Czekala'
author = 'Ian Czekala'

version = psoap.__version__
release = psoap.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['.build']

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# taken from https://github.com/dfm/celerite/blob/master/docs/conf.py
# Readthedocs.
import sphinx_rtd_theme
html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

html_context = dict(
    display_github=True,
    github_user="iancze",
    github_repo="psoap",
    github_version="master",
    conf_py_path="/doc/",
)

html_static_path = ['.static']
